/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/pg/catkin_ws/src/epos2_control/msg/HubFlow.msg
 *
 */


#ifndef EPOS2_CONTROL_MESSAGE_HUBFLOW_H
#define EPOS2_CONTROL_MESSAGE_HUBFLOW_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace epos2_control
{
template <class ContainerAllocator>
struct HubFlow_
{
  typedef HubFlow_<ContainerAllocator> Type;

  HubFlow_()
    : hub(0.0)
    , flow(0.0)  {
    }
  HubFlow_(const ContainerAllocator& _alloc)
    : hub(0.0)
    , flow(0.0)  {
    }



   typedef float _hub_type;
  _hub_type hub;

   typedef float _flow_type;
  _flow_type flow;




  typedef boost::shared_ptr< ::epos2_control::HubFlow_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::epos2_control::HubFlow_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct HubFlow_

typedef ::epos2_control::HubFlow_<std::allocator<void> > HubFlow;

typedef boost::shared_ptr< ::epos2_control::HubFlow > HubFlowPtr;
typedef boost::shared_ptr< ::epos2_control::HubFlow const> HubFlowConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::epos2_control::HubFlow_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::epos2_control::HubFlow_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace epos2_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'epos2_control': ['/home/pg/catkin_ws/src/epos2_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::epos2_control::HubFlow_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::epos2_control::HubFlow_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::epos2_control::HubFlow_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::epos2_control::HubFlow_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::epos2_control::HubFlow_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::epos2_control::HubFlow_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::epos2_control::HubFlow_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0937cbb35470b309d903626d01eaffea";
  }

  static const char* value(const ::epos2_control::HubFlow_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0937cbb35470b309ULL;
  static const uint64_t static_value2 = 0xd903626d01eaffeaULL;
};

template<class ContainerAllocator>
struct DataType< ::epos2_control::HubFlow_<ContainerAllocator> >
{
  static const char* value()
  {
    return "epos2_control/HubFlow";
  }

  static const char* value(const ::epos2_control::HubFlow_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::epos2_control::HubFlow_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 hub\n\
float32 flow\n\
";
  }

  static const char* value(const ::epos2_control::HubFlow_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::epos2_control::HubFlow_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.hub);
      stream.next(m.flow);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct HubFlow_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::epos2_control::HubFlow_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::epos2_control::HubFlow_<ContainerAllocator>& v)
  {
    s << indent << "hub: ";
    Printer<float>::stream(s, indent + "  ", v.hub);
    s << indent << "flow: ";
    Printer<float>::stream(s, indent + "  ", v.flow);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EPOS2_CONTROL_MESSAGE_HUBFLOW_H
