# -*- Den Contiki-Pfad hier eintragen -*-
CONTIKI_PROJECT = IOTest
CONTIKI =D:/Entwicklung/contiki-2.7

all: IOTest 

 PROJECT_SOURCEFILES += drivers/bolt_drv.c interface/bolt_int.c drivers/photosensor_drv.c interface/photosensor_int.c drivers/uart_drv.c

include $(CONTIKI)/Makefile.include

