# -*- Den Contiki-Pfad hier eintragen -*-

CONTIKI = C:/Users/vmsieben/Documents/Projektgruppe/contiki-2.7

all: Materialfluss

PROJECT_SOURCEFILES += drivers/bolt_drv.c interface/bolt_int.c 
PROJECT_SOURCEFILES += drivers/photosensor_drv.c interface/photosensor_int.c 
PROJECT_SOURCEFILES += drivers/uart_drv.c service/com_service.c
PROJECT_SOURCEFILES += drivers/extflash_drv.c service/extflash_service.c interface/extflash_int.c interface/MemoryInterface/MemoryInterface.c
PROJECT_SOURCEFILES += drivers/proficonn_driver.c
PROJECT_SOURCEFILES += drivers/radio_drv.c

include $(CONTIKI)/Makefile.include

