# -*- Den Contiki-Pfad hier eintragen -*-

CONTIKI =C:/Users/Malte/Documents/Projektgruppe/contiki-2.7

all: IOTest

PROJECT_SOURCEFILES += drivers/bolt_drv.c drivers/extflash_drv.c drivers/photosensor_drv.c drivers/proficonn_driver.c drivers/uart_drv.c drivers/radio_drv.c interface/bolt_int.c interface/photosensor_int.c service/com_service.c service/extflash_service.c interface/radio_int.c

include $(CONTIKI)/Makefile.include

